# Generated by Django 5.0.4 on 2024-07-30 00:53

import django.db.models.deletion
import users.Enums.userType
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_type', models.IntegerField(choices=[(1, 'SELLER'), (2, 'BUYER')], default=users.Enums.userType.UserType['BUYER'])),
                ('wallet_balance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
